import { PROJECT_ROLES } from "../../features/projects/constants/projectRoles";
import { PERMISSIONS } from "../constants/permissions";

export const ROLE_PERMISSIONS = {
  // Project Roles Permissions
  [PROJECT_ROLES.PROJECT_ADMIN]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.ADD_MEMBER_TO_PROJECT,
    PERMISSIONS.REMOVE_PROJECT_MEMBER,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
  ],

  [PROJECT_ROLES.MEMBER]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
  ],
};
