import { PERMISSIONS, type Permission } from "../constants/permissions";
import {
  WORKSPACE_ROLES,
  type WorkspaceRole,
} from "../constants/workSpaceRoles";

export const ROLE_PERMISSIONS = {
  // Workspace Role Permissions
  [WORKSPACE_ROLES.OWNER]: [
    PERMISSIONS.INVITATION_CREATE,
    PERMISSIONS.INVITATION_CANCEL,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,

    PERMISSIONS.ADD_MEMBER_TO_PROJECT,
    PERMISSIONS.MANAGE_PROJECT_MEMBER,

    PERMISSIONS.WORKSPACE_CREATE,
    PERMISSIONS.MANAGE_WORKSPACE_MEMBER,
  ],

  [WORKSPACE_ROLES.ADMIN]: [
    PERMISSIONS.INVITATION_CREATE,
    PERMISSIONS.INVITATION_CANCEL,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.ADD_MEMBER_TO_PROJECT,
    PERMISSIONS.MANAGE_PROJECT_MEMBER,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,

    PERMISSIONS.MANAGE_WORKSPACE_MEMBER,
  ],

  [WORKSPACE_ROLES.MEMBER]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
  ],
} satisfies Record<WorkspaceRole, readonly Permission[]>;
